<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>tomware.Microwf.AspNetCoreEngine</AssemblyName>
    <RootNamespace>tomware.Microwf.Engine</RootNamespace>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Description>
      An ASP.NET Core with EF Core way of leveraging tomware.Microwf.Core in a Web Api.
    </Description>
    <RepositoryUrl>https://github.com/thomasduft/microwf</RepositoryUrl>
    <Authors>Thomas Duft</Authors>
    <Company>tomWare SOLUTIONS</Company>
    <RepositoryType>git</RepositoryType>
    <Copyright>2018 tomWare SOLUTIONS</Copyright>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <PackageIcon>icon.png</PackageIcon>
    <PackageTags>StateMachine Workflow micro</PackageTags>
    <PackageProjectUrl>https://github.com/thomasduft/microwf</PackageProjectUrl>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>

    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\microwf.Core\microwf.Core.csproj" />
    <ProjectReference Include="..\microwf.Domain\microwf.Domain.csproj" />
    <ProjectReference Include="..\microwf.Infrastructure\microwf.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE.md" Pack="true" PackagePath="" />
    <None Include="..\..\icon.png" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
