// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Domain;

namespace WebApi.Migrations
{
    [DbContext(typeof(DomainContext))]
    [Migration("20180626074718_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("tomware.Microwf.Engine.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Assignee");

                    b.Property<int>("CorrelationId");

                    b.Property<DateTime?>("DueDate");

                    b.Property<string>("State")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Workflow");
                });

            modelBuilder.Entity("tomware.Microwf.Engine.WorkflowContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Context");

                    b.Property<int>("WorkflowId");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId")
                        .IsUnique();

                    b.ToTable("WorkflowContext");
                });

            modelBuilder.Entity("WebApi.Workflows.Holiday.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Assignee")
                        .IsRequired();

                    b.Property<DateTime?>("From");

                    b.Property<string>("Requester")
                        .IsRequired();

                    b.Property<string>("State")
                        .IsRequired();

                    b.Property<string>("Superior");

                    b.Property<DateTime?>("To");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Holiday");
                });

            modelBuilder.Entity("tomware.Microwf.Engine.WorkflowContext", b =>
                {
                    b.HasOne("tomware.Microwf.Engine.Workflow", "Workflow")
                        .WithOne("WorkflowContext")
                        .HasForeignKey("tomware.Microwf.Engine.WorkflowContext", "WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
